import os
import time
from JARVIS.memory.system import MemorySystem
from JARVIS.intelligence.neural_hub.core import NeuralHub, NeuralState, ProcessingContext, ActivationMode
from JARVIS.plugins.research_ore.engine import ResearchEngine
from JARVIS.core.ule.realizer import ule_realizer

def run_real_world_thesis_ule():
    print(">>> JARVIS MISSION: AUTOMATED THESIS GENERATION (TARGET: MAREY) [ULE ENABLED] <<<\n")

    # 1. Initialize Components
    memory = MemorySystem()
    neural = NeuralHub()
    state = NeuralState(user_id="researcher", project_id="thesis_auto")
    ctx = ProcessingContext()

    # --------------------------------------------------------------------------------
    # STEP 1: INITIALIZATION
    # --------------------------------------------------------------------------------
    print("\n[USER] Start a new project: Write a thesis about the MAREY repository logic.")
    res = neural.process("Start a new project: Write a thesis about the MAREY repository logic.", ctx, state, memory)

    if res.should_propose:
        memory.log_event("USER", "START_PROJECT", "project-thesis", {"topic": "MAREY Thesis"})
        memory.add_relation("project-thesis", "MAREY_REPO", "depends_on")

    # --------------------------------------------------------------------------------
    # STEP 2: CODE ANALYSIS
    # --------------------------------------------------------------------------------
    repo_path = "MAREY"
    if os.path.exists(repo_path):
        structure = []
        for root, dirs, files in os.walk(repo_path):
            if ".git" in root: continue
            for f in files:
                if f.endswith(".py"):
                    structure.append(f)

        # Populate Memory
        print(f"[VISION] Scanned {len(structure)} files.")
        memory.log_event("SYSTEM", "ANALYZE_CODE", "marey-codebase", {"files": structure, "topic": "MAREY Architecture"})

        # Create Knowledge Nodes
        memory.log_event("SYSTEM", "EXTRACT_FACT", "fact-adaptive", {"content": "MAREY uses Adaptive Processing", "topic": "Adaptive Vision"})
        memory.add_relation("MAREY_REPO", "fact-adaptive", "contains")

    # --------------------------------------------------------------------------------
    # STEP 3: RESEARCH (ORE)
    # --------------------------------------------------------------------------------
    print("\n[USER] Research academic papers on 'Adaptive Saccadic Vision'.")
    papers = [
        {"title": "Efficient Saccadic Vision for Edge Devices", "summary": "low-res scanning viability"},
        {"title": "Hardware-Aware Neural Architecture Search", "summary": "Optimizing models for specific CPUs"}
    ]

    for p in papers:
        # Store in Memory
        print(f"[ORE] Ingested: {p['title']}")
        # Note: We store the dict as payload
        memory.log_event("ORE", "INGEST_PAPER", f"paper-{hash(p['title'])}", p)
        memory.add_relation("project-thesis", f"paper-{hash(p['title'])}", "depends_on")

    # --------------------------------------------------------------------------------
    # STEP 4: SYNTHESIS & REALIZATION (ULE)
    # --------------------------------------------------------------------------------
    print("\n[USER] Write the Abstract using ULE.")

    # 1. Retrieve Context
    print("[MEMORY] Spreading Activation from 'project-thesis'...")
    # Retrieve mock nodes since spread_activation returns IDs and weights, we need the payloads
    # In a real app we'd fetch from DB. Here we reconstruct from the events we just logged (simulated)

    context_nodes = [
        {"type": "project", "payload": {"topic": "MAREY Thesis"}},
        {"type": "codebase", "payload": {"files": structure, "topic": "MAREY Architecture"}},
        {"type": "fact", "payload": {"content": "Adaptive Processing", "focus": "Adaptive Processing"}},
        {"type": "paper", "payload": papers[0]}
    ]

    # 2. Realize
    output = ule_realizer.generate_report(context_nodes)

    print("\n>>> FINAL OUTPUT (Generated by ULE) <<<")
    print(output)
    print(">>> MISSION COMPLETE <<<")

if __name__ == "__main__":
    run_real_world_thesis_ule()
